apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-replica
  labels:
    app: tomcat-app-replica
    type: fibi-base




spec:
  template:
    metadata:
      name: tomcat-pod
      labels:
        app: tomcat-app
        type: fibi-base
    spec:
      containers:
        - name: tomcat-container
          image: tomcat:9.0.22
          ports:
            - containerPort: 8080



  replicas: 3
  selector:
    matchLabels:
      type: fibi-base
